
# exceptions/custom_exceptions.py

from .custom_exception import TrackingNumberNotFoundException
from .custom_exception import InvalidEmployeeIdException